### ISSUE TITLE
Webview2 

### ISSUE THREAD

**Issue by YILDIRIMERAY** [ebubekirbastama/System-Web-Helpers-JsonDecode-Kullanimi#1]
Yazdığınız kodun tamamını paylaşmanız mümkün müdür.
Aşağıdaki kodu nedense çalıştırmayı başaramadım.

İyi çalışmalar dilerim.

            var html = await webView2.CoreWebView2.ExecuteScriptAsync("document.body.outerHTML");
            var htmldecoded = System.Web.Helpers.Json.Decode(html);

**Comment by ebubekirbastama** [comment]
private void Vericekk()
{
    var ss = Json.Decode(veritoplama(i));
    foreach (var item in ss.products.Data)
    {
        name = item.attributes.name;

    }

}

Bu metod çalışıyor Json.Decode(jsonveri)  json verisini eklerseniz çalışır sizin eklediğiniz veri nedir
